# Numpy module

In [2]:
import numpy as np

### Creating a numpy array

In [4]:
a=np.array([1,2,3]) # with the help of numpy convert values of list to array 
print(a)
print(type(a)) # type of object
print(a.dtype) # data type

[1 2 3]
<class 'numpy.ndarray'>
int32


### Creating a 2-d numpy array

In [3]:
#multiple row multiple column 
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
#chnage data type of an array
a=np.array([1,2,3,4], dtype= complex)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [4]:
#multiple row multiple column 
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#check dimension of array
print(a.ndim)

2


In [6]:
# check shape 
print(a.shape)

(3, 3)


In [7]:
#check itemsize
print(a.itemsize)

8


In [14]:
 a=np.array([[1,2],[4,5],[7,8]])
#To change shape
b=a.reshape(2,3)
print(b)

[[1 2 4]
 [5 7 8]]


In [19]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
#indexing 
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(a[0]) # 1st row

[1 2 3]


In [17]:
print(a[0][1]) # particular element value

2


In [16]:
print(a[0,1]) #particular element

2


In [20]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
#indexing 
print(a)
print(a[0]) # 1st row
print(a[0][1]) # particular element value
print(a[0,1]) #particular element value

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
2
2


In [21]:
#slicing
print("\n")
print(a[:,:])
print(a[: ,0]) #column(all row  but column 1)
print(a[:1, :2])
print(a[:2,2])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
[[1 2]]
[3 6]


In [42]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.max())
print(a.min())
print(a.sum())
print(a.sum(axis=0)) #sum column wise
print(a.sum(axis=1)) #sum row wise

9
1
45
[12 15 18]
[ 6 15 24]


In [24]:
#mathmatical operation
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(np.sqrt(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
