In [2]:

#use of Groupby :Data Sort

import pandas as pd
#import numpy as np

x={'Name':['Alok','Rahul','Ram','Ramesh','Amit','Mudit'],'Percentage':[98,95,87,75,67,89],'Course':['B.Tech','B.Sc','BA','B.ED','BA','B.sc']}

y=pd.DataFrame(x)

a=y.groupby('Course')

print(a['Percentage'].agg(np.mean))




Name
Alok      98
Rahul     95
Ram       87
Ramesh    75
Name: Percentage, dtype: int64


In [33]:
#use head() function to get the values of rows

import pandas as pd
#import numpy as np

x={'Name':['Alok','Rahul','Ram','Ramesh','Amit','Mudit'],'Percentage':[98,95,87,75,67,89],'Course':['B.Tech','B.Sc','BA','B.ED','BA','B.sc']}

y=pd.DataFrame(x)
print(y.head(2))



    Name  Percentage  Course
0   Alok          98  B.Tech
1  Rahul          95    B.Sc


In [9]:
# to_numpy() used to convert data frame to numpy


import pandas as pd
x=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],columns = ['x','y','z'])

print(x)

y=x.to_numpy()
print("\n",y)

    x   y   z
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
# to give user define value to NAN  (undefine or missing) value

import pandas as pd
x=pd.DataFrame({'Id':[12,23,45,67,None]})
print(x)

x.fillna(value=34,inplace=True)
print("\n",x)

     Id
0  12.0
1  23.0
2  45.0
3  67.0
4   NaN

      Id
0  12.0
1  23.0
2  45.0
3  67.0
4  34.0


In [34]:
import pandas as pd

x=pd.DataFrame([[np.nan,np.nan,np.nan,5,8],[12,45,np.nan,89,65],[np.nan,np.nan,6,5,4]])
print(x)

      0     1    2   3   4
0   NaN   NaN  NaN   5   8
1  12.0  45.0  NaN  89  65
2   NaN   NaN  6.0   5   4
